version: '3.8'
services:
  app:
    build: .
    runtime: nvidia  # Specify the runtime for NVIDIA
    volumes:
      - MUSICGEN_ROOT:/app/MUSICGEN_ROOT
      - HF_HOME:/app/HF_HOME
      - container_cache:/root/.cache
      - venv:/app/audio-webui/venv
    command: "/app/run.sh"
    environment:
      - NVIDIA_VISIBLE_DEVICES: all 
      - ENABLE_CUDA: '1'  # Enable CUDA
    env_file:
      - .env
    ports:
      - "9001:7860"  # Changed to 9001 to avoid conflict
    stdin_open: true
    tty: true

volumes:
  MUSICGEN_ROOT:
  HF_HOME:
  container_cache:
  venv:
