version: '3.8'
services:
  app:
    build: .
    runtime: nvidia  # Specify the runtime for NVIDIA
    environment:
      ENABLE_CUDA: '1'  # Enable CUDA
      NVIDIA_VISIBLE_DEVICES: 1  # Add this line
    volumes:
      - MUSICGEN_ROOT:/app/MUSICGEN_ROOT
      - HF_HOME:/app/HF_HOME
      - container_cache:/root/.cache
      - venv:/app/audio-webui/venv
    command: "/app/run.sh"
    env_file:
      - .env
    ports:
      - "5859:7860"  # Changed to 5859 to avoid conflict
    stdin_open: true
    tty: true
    restart: on-failure:0  # Add this line to restart on failure, similar to Weaviate

volumes:
  MUSICGEN_ROOT:
  HF_HOME:
  container_cache:
  venv:
